services:
    gateway:
        env_file:
            - .env.dev
        working_dir: /app
        volumes:
            - ./packages/gateway/src:/app/packages/gateway/src
            - ./packages/shared/src:/app/packages/shared/src
        command: ['npm', 'run', 'dev:container:gateway']
        environment:
            NODE_ENV: development
        ports:
            - '3000:3000'
            - '9229:9229'
    auth-service:
        env_file:
            - .env.dev
        working_dir: /app
        volumes:
            - ./packages/services/auth-service/src:/app/packages/services/auth-service/src
            - ./packages/shared/src:/app/packages/shared/src
        command: ['npm', 'run', 'dev:container:auth']
        environment:
            NODE_ENV: development
        ports:
            - '9230:9230'
    book-service:
        env_file:
            - .env.dev
        working_dir: /app
        volumes:
            - ./packages/services/book-service/src:/app/packages/services/book-service/src
            - ./packages/shared/src:/app/packages/shared/src
        command: ['npm', 'run', 'dev:container:book']
        environment:
            NODE_ENV: development
        ports:
            - '9231:9231'
